
name: Deploy Rust Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build project
        run: cargo build --release

      - name: Prepare artifact
        run: |
          mkdir -p artifact
          cp target/release/auth-api artifact/

      - name: Deploy to server via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "artifact/auth-api"
          target: ${{ secrets.DEPLOY_PATH }}
          strip_components: 1

      - name: Run deployed binary on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            chmod +x auth-api
            ./auth-api &> /dev/null &
            echo "Deployed and running auth-api on server."
